services:
  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: 1111
    ports:
      - "3307:3306" # 3306 on the host is taken by local MySQL
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - products-microservice-network
    hostname: mysql-host-productsmicroservice

  products-microservice:
    build:
      context: .
      dockerfile: ProductsMicroService.API/Dockerfile
    environment:
      ASPNETCORE_HTTP_PORTS: 8080
      MYSQL_HOST: mysql-host-productsmicroservice
      MYSQL_PASSWORD: 1111
    ports:
      - "8080:8080"
    networks:
      - products-microservice-network
    depends_on:
      - mysql

networks:
  products-microservice-network:
    driver: bridge
