services:
  mongodb:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - orders-microservice-network
    hostname: mongodb-host-ordersmicroservice

  orders-microservice:
    image: khalidalhadi/ecommerce-orders-microservice:v1.0
    build:
      context: .
      dockerfile: OrdersMicroservice.API/Dockerfile
    environment:
      MONGODB_HOST: mongodb-host-ordersmicroservice
      MONGODB_PORT: 27017
    ports:
      - "7000:8080" # 8080 on the host is used by the Products service
    networks:
      - orders-microservice-network
    depends_on:
      - mongodb

networks:
  orders-microservice-network:
    driver: bridge
